version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: php_pro_nginx
    build:
      dockerfile: ./docker/configs/nginx/Dockerfile
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./docker/configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/srv/src/
    links:
      - php

  php:
    build:
      context: ./
      dockerfile: ./docker/configs/php/Dockerfile
    container_name: php_pro_php
    restart: always
    volumes:
      - ./:/srv/src/
    expose:
      - 9003
    links:
      - db_mysql

  db_mysql:
    image: mysql:latest
    container_name: php_pro_mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_CONNECTION: sql11.freemysqlhosting.net
      MYSQL_ROOT_PASSWORD: sql11691868
      MYSQL_USER: sql11691868
      MYSQL_DATABASE: sql11691868
      MYSQL_PASSWORD: tVGGtGP62E